# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Green's Opinion
email: greensopinion@gmail.com
description: Green's Opinion provides insight and opinions on software and open source.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://greensopinion.com" # the base hostname & protocol for your site
twitter_username: dgreen
github_username:  greensopinion
disqusid: greensopinion

collections:
  - posts_erw

collections:
  posts_erw:
    output: true
    permalink: /epic-ride-weather/post/:path/

defaults:
  - scope:
      path: ""
      type: posts_erw
    values:
      layout: post_erw
      brand: epicrideweather
      headerlink: /epic-ride-weather/
      headertitle: Epic Ride Weather
      includewrapper: true
      comments: false
      author: David Green

# Build settings
markdown: kramdown

pages_list:
  Blog: '/blog'
  Archive: '/archive'
  About: '/about'
