# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Green's Opinion
email: dgreen99@gmail.com
description: Green's Opinion, by David Green.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://greensopinion.github.io" # the base hostname & protocol for your site
twitter_username: dgreen
github_username:  greensopinion

# Build settings
markdown: kramdown
